name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "mimapi"
          heroku_email: ${{secrets.HEROKU_API_MAIL}}
          usedocker: true
        env:
          DB_URI: ${{secrets.DB}}
          FASTAPI_SIMPLE_SECURITY_SECRET: ${{secrets.FASTAPI_SIMPLE_SECURITY_SECRET}}